name: cinema_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

#--------------------------- PACKAGES ---------------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  http: ^1.2.2
  intl: ^0.19.0
  logger: ^2.4.0
  url_launcher: ^6.3.1
  lottie: ^3.1.3
  connectivity_plus: ^6.1.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  file_picker: ^8.1.4
  image: ^4.3.0
  flutter_screenutil: ^5.9.3
  responsive_builder: ^0.7.1

  # Firebase 
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_sign_in: ^6.2.2
  
  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_riverpod: ^2.6.1
  
  # Add flutter_native_splash here to make it a runtime dependency
  flutter_native_splash: ^2.2.7
  flutter_dotenv: ^5.2.1

#-------------------------- PACKAGES END -------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo_app.png"
  remove_alpha_ios: true
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logos/logo_app.png"

flutter:
  uses-material-design: true

#-------------------------- ASSETS -------------------------#
  assets:
    - .env
    - assets/logos/
    - assets/images/
    - assets/icons/
    - assets/images/on_board_images/
    - assets/icons/categories/
    - assets/images/movie_posters/
    - assets/images/others/
    - assets/images/animations/
    - assets/logos/pause_light.png
    - assets/logos/pause_dark.png
    - assets/images/user/defaultUser.png

#--------------------------- FONTS --------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
