// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnvLJIq14y_Jw6Yl38JcE3kk9YmylUAyY',
    appId: '1:97403841289:web:59e99d678be653696c41d8',
    messagingSenderId: '97403841289',
    projectId: 'pause-app-38195',
    authDomain: 'pause-app-38195.firebaseapp.com',
    storageBucket: 'pause-app-38195.firebasestorage.app',
    measurementId: 'G-ST9F20FQBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ3kQzqRzWjwiMjYP048Xxb3INcZmo1aY',
    appId: '1:97403841289:android:a268e0122c224efa6c41d8',
    messagingSenderId: '97403841289',
    projectId: 'pause-app-38195',
    storageBucket: 'pause-app-38195.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS2py8II3jk0ywxzM7rGk8EZLTmVKi1-s',
    appId: '1:97403841289:ios:f848b4563c408e486c41d8',
    messagingSenderId: '97403841289',
    projectId: 'pause-app-38195',
    storageBucket: 'pause-app-38195.firebasestorage.app',
    androidClientId: '97403841289-jqpro92s7e6aq6fh4flsdmn0cs4paife.apps.googleusercontent.com',
    iosClientId: '97403841289-6na3jghaehqr7itfbtm5gtfn4t6joldn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnvLJIq14y_Jw6Yl38JcE3kk9YmylUAyY',
    appId: '1:97403841289:web:1d4dbe569912b3cc6c41d8',
    messagingSenderId: '97403841289',
    projectId: 'pause-app-38195',
    authDomain: 'pause-app-38195.firebaseapp.com',
    storageBucket: 'pause-app-38195.firebasestorage.app',
    measurementId: 'G-4R9KKPVRDX',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS2py8II3jk0ywxzM7rGk8EZLTmVKi1-s',
    appId: '1:97403841289:ios:f848b4563c408e486c41d8',
    messagingSenderId: '97403841289',
    projectId: 'pause-app-38195',
    storageBucket: 'pause-app-38195.firebasestorage.app',
    androidClientId: '97403841289-jqpro92s7e6aq6fh4flsdmn0cs4paife.apps.googleusercontent.com',
    iosClientId: '97403841289-6na3jghaehqr7itfbtm5gtfn4t6joldn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cinemaApp',
  );

}